// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.1
// source: grpc/tradeapi/v1/assets/assets_service.proto

package assets_service

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	date "google.golang.org/genproto/googleapis/type/date"
	decimal "google.golang.org/genproto/googleapis/type/decimal"
	interval "google.golang.org/genproto/googleapis/type/interval"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Тип опциона
type Option_Type int32

const (
	// Неопределенное значение
	Option_TYPE_UNSPECIFIED Option_Type = 0
	// Колл
	Option_TYPE_CALL Option_Type = 1
	// Пут
	Option_TYPE_PUT Option_Type = 2
)

// Enum value maps for Option_Type.
var (
	Option_Type_name = map[int32]string{
		0: "TYPE_UNSPECIFIED",
		1: "TYPE_CALL",
		2: "TYPE_PUT",
	}
	Option_Type_value = map[string]int32{
		"TYPE_UNSPECIFIED": 0,
		"TYPE_CALL":        1,
		"TYPE_PUT":         2,
	}
)

func (x Option_Type) Enum() *Option_Type {
	p := new(Option_Type)
	*p = x
	return p
}

func (x Option_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Option_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_grpc_tradeapi_v1_assets_assets_service_proto_enumTypes[0].Descriptor()
}

func (Option_Type) Type() protoreflect.EnumType {
	return &file_grpc_tradeapi_v1_assets_assets_service_proto_enumTypes[0]
}

func (x Option_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Option_Type.Descriptor instead.
func (Option_Type) EnumDescriptor() ([]byte, []int) {
	return file_grpc_tradeapi_v1_assets_assets_service_proto_rawDescGZIP(), []int{10, 0}
}

// Запрос получения списка доступных бирж
type ExchangesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExchangesRequest) Reset() {
	*x = ExchangesRequest{}
	mi := &file_grpc_tradeapi_v1_assets_assets_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExchangesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExchangesRequest) ProtoMessage() {}

func (x *ExchangesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_tradeapi_v1_assets_assets_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExchangesRequest.ProtoReflect.Descriptor instead.
func (*ExchangesRequest) Descriptor() ([]byte, []int) {
	return file_grpc_tradeapi_v1_assets_assets_service_proto_rawDescGZIP(), []int{0}
}

// Список доступных бирж
type ExchangesResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Информация о бирже
	Exchanges     []*Exchange `protobuf:"bytes,1,rep,name=exchanges,proto3" json:"exchanges,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExchangesResponse) Reset() {
	*x = ExchangesResponse{}
	mi := &file_grpc_tradeapi_v1_assets_assets_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExchangesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExchangesResponse) ProtoMessage() {}

func (x *ExchangesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_tradeapi_v1_assets_assets_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExchangesResponse.ProtoReflect.Descriptor instead.
func (*ExchangesResponse) Descriptor() ([]byte, []int) {
	return file_grpc_tradeapi_v1_assets_assets_service_proto_rawDescGZIP(), []int{1}
}

func (x *ExchangesResponse) GetExchanges() []*Exchange {
	if x != nil {
		return x.Exchanges
	}
	return nil
}

// Запрос получения списка доступных инструментов
type AssetsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssetsRequest) Reset() {
	*x = AssetsRequest{}
	mi := &file_grpc_tradeapi_v1_assets_assets_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssetsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssetsRequest) ProtoMessage() {}

func (x *AssetsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_tradeapi_v1_assets_assets_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssetsRequest.ProtoReflect.Descriptor instead.
func (*AssetsRequest) Descriptor() ([]byte, []int) {
	return file_grpc_tradeapi_v1_assets_assets_service_proto_rawDescGZIP(), []int{2}
}

// Список доступных инструментов
type AssetsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Информация об инструменте
	Assets        []*Asset `protobuf:"bytes,1,rep,name=assets,proto3" json:"assets,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssetsResponse) Reset() {
	*x = AssetsResponse{}
	mi := &file_grpc_tradeapi_v1_assets_assets_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssetsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssetsResponse) ProtoMessage() {}

func (x *AssetsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_tradeapi_v1_assets_assets_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssetsResponse.ProtoReflect.Descriptor instead.
func (*AssetsResponse) Descriptor() ([]byte, []int) {
	return file_grpc_tradeapi_v1_assets_assets_service_proto_rawDescGZIP(), []int{3}
}

func (x *AssetsResponse) GetAssets() []*Asset {
	if x != nil {
		return x.Assets
	}
	return nil
}

// Запрос получения цепочки опционов
type OptionsChainRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Символ базового актива опциона
	UnderlyingSymbol string `protobuf:"bytes,1,opt,name=underlying_symbol,json=underlyingSymbol,proto3" json:"underlying_symbol,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *OptionsChainRequest) Reset() {
	*x = OptionsChainRequest{}
	mi := &file_grpc_tradeapi_v1_assets_assets_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OptionsChainRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OptionsChainRequest) ProtoMessage() {}

func (x *OptionsChainRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_tradeapi_v1_assets_assets_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OptionsChainRequest.ProtoReflect.Descriptor instead.
func (*OptionsChainRequest) Descriptor() ([]byte, []int) {
	return file_grpc_tradeapi_v1_assets_assets_service_proto_rawDescGZIP(), []int{4}
}

func (x *OptionsChainRequest) GetUnderlyingSymbol() string {
	if x != nil {
		return x.UnderlyingSymbol
	}
	return ""
}

// Информация о цепочке опционов
type OptionsChainResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Символ опциона
	Symbol string `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	// Информация об опционе
	Options       []*Option `protobuf:"bytes,2,rep,name=options,proto3" json:"options,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OptionsChainResponse) Reset() {
	*x = OptionsChainResponse{}
	mi := &file_grpc_tradeapi_v1_assets_assets_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OptionsChainResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OptionsChainResponse) ProtoMessage() {}

func (x *OptionsChainResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_tradeapi_v1_assets_assets_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OptionsChainResponse.ProtoReflect.Descriptor instead.
func (*OptionsChainResponse) Descriptor() ([]byte, []int) {
	return file_grpc_tradeapi_v1_assets_assets_service_proto_rawDescGZIP(), []int{5}
}

func (x *OptionsChainResponse) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *OptionsChainResponse) GetOptions() []*Option {
	if x != nil {
		return x.Options
	}
	return nil
}

// Запрос получения расписания инструмента
type ScheduleRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Символ инструмента
	Symbol        string `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScheduleRequest) Reset() {
	*x = ScheduleRequest{}
	mi := &file_grpc_tradeapi_v1_assets_assets_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScheduleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScheduleRequest) ProtoMessage() {}

func (x *ScheduleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_tradeapi_v1_assets_assets_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScheduleRequest.ProtoReflect.Descriptor instead.
func (*ScheduleRequest) Descriptor() ([]byte, []int) {
	return file_grpc_tradeapi_v1_assets_assets_service_proto_rawDescGZIP(), []int{6}
}

func (x *ScheduleRequest) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

// Расписание инструмента
type ScheduleResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Символ инструмента
	Symbol string `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	// Сессии инструмента
	Sessions      []*ScheduleResponse_Sessions `protobuf:"bytes,2,rep,name=sessions,proto3" json:"sessions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScheduleResponse) Reset() {
	*x = ScheduleResponse{}
	mi := &file_grpc_tradeapi_v1_assets_assets_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScheduleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScheduleResponse) ProtoMessage() {}

func (x *ScheduleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_tradeapi_v1_assets_assets_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScheduleResponse.ProtoReflect.Descriptor instead.
func (*ScheduleResponse) Descriptor() ([]byte, []int) {
	return file_grpc_tradeapi_v1_assets_assets_service_proto_rawDescGZIP(), []int{7}
}

func (x *ScheduleResponse) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *ScheduleResponse) GetSessions() []*ScheduleResponse_Sessions {
	if x != nil {
		return x.Sessions
	}
	return nil
}

// Информация о бирже
type Exchange struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Идентификатор биржи mic
	Mic string `protobuf:"bytes,1,opt,name=mic,proto3" json:"mic,omitempty"`
	// Наименование биржи
	Name          string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Exchange) Reset() {
	*x = Exchange{}
	mi := &file_grpc_tradeapi_v1_assets_assets_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Exchange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Exchange) ProtoMessage() {}

func (x *Exchange) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_tradeapi_v1_assets_assets_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Exchange.ProtoReflect.Descriptor instead.
func (*Exchange) Descriptor() ([]byte, []int) {
	return file_grpc_tradeapi_v1_assets_assets_service_proto_rawDescGZIP(), []int{8}
}

func (x *Exchange) GetMic() string {
	if x != nil {
		return x.Mic
	}
	return ""
}

func (x *Exchange) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// Информация об инструменте
type Asset struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Символ инструмента ticker@mic
	Symbol string `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	// Идентификатор инструмента
	Id string `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	// Тикер инструмента
	Ticker string `protobuf:"bytes,3,opt,name=ticker,proto3" json:"ticker,omitempty"`
	// mic идентификатор биржи
	Mic string `protobuf:"bytes,4,opt,name=mic,proto3" json:"mic,omitempty"`
	// Isin идентификатор инструмента
	Isin string `protobuf:"bytes,5,opt,name=isin,proto3" json:"isin,omitempty"`
	// Тип инструмента
	Type string `protobuf:"bytes,6,opt,name=type,proto3" json:"type,omitempty"`
	// Наименование инструмента
	Name          string `protobuf:"bytes,7,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Asset) Reset() {
	*x = Asset{}
	mi := &file_grpc_tradeapi_v1_assets_assets_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Asset) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Asset) ProtoMessage() {}

func (x *Asset) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_tradeapi_v1_assets_assets_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Asset.ProtoReflect.Descriptor instead.
func (*Asset) Descriptor() ([]byte, []int) {
	return file_grpc_tradeapi_v1_assets_assets_service_proto_rawDescGZIP(), []int{9}
}

func (x *Asset) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *Asset) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Asset) GetTicker() string {
	if x != nil {
		return x.Ticker
	}
	return ""
}

func (x *Asset) GetMic() string {
	if x != nil {
		return x.Mic
	}
	return ""
}

func (x *Asset) GetIsin() string {
	if x != nil {
		return x.Isin
	}
	return ""
}

func (x *Asset) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Asset) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// Инфомация об опционе
type Option struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Символ инструмента
	Symbol string `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	// Тип инструмента
	Type Option_Type `protobuf:"varint,2,opt,name=type,proto3,enum=grpc.tradeapi.v1.assets.Option_Type" json:"type,omitempty"`
	// Лот, количество базового актива в инструменте
	ContractSize *decimal.Decimal `protobuf:"bytes,4,opt,name=contract_size,json=contractSize,proto3" json:"contract_size,omitempty"`
	// Дата начала торговли
	TradeFirstDay *date.Date `protobuf:"bytes,5,opt,name=trade_first_day,json=tradeFirstDay,proto3" json:"trade_first_day,omitempty"`
	// Дата экспирации
	TradeLastDay *date.Date `protobuf:"bytes,6,opt,name=trade_last_day,json=tradeLastDay,proto3" json:"trade_last_day,omitempty"`
	// Цена исполнения опциона
	Strike *decimal.Decimal `protobuf:"bytes,7,opt,name=strike,proto3" json:"strike,omitempty"`
	// Множитель опциона
	Multiplier    *decimal.Decimal `protobuf:"bytes,9,opt,name=multiplier,proto3" json:"multiplier,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Option) Reset() {
	*x = Option{}
	mi := &file_grpc_tradeapi_v1_assets_assets_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Option) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Option) ProtoMessage() {}

func (x *Option) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_tradeapi_v1_assets_assets_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Option.ProtoReflect.Descriptor instead.
func (*Option) Descriptor() ([]byte, []int) {
	return file_grpc_tradeapi_v1_assets_assets_service_proto_rawDescGZIP(), []int{10}
}

func (x *Option) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *Option) GetType() Option_Type {
	if x != nil {
		return x.Type
	}
	return Option_TYPE_UNSPECIFIED
}

func (x *Option) GetContractSize() *decimal.Decimal {
	if x != nil {
		return x.ContractSize
	}
	return nil
}

func (x *Option) GetTradeFirstDay() *date.Date {
	if x != nil {
		return x.TradeFirstDay
	}
	return nil
}

func (x *Option) GetTradeLastDay() *date.Date {
	if x != nil {
		return x.TradeLastDay
	}
	return nil
}

func (x *Option) GetStrike() *decimal.Decimal {
	if x != nil {
		return x.Strike
	}
	return nil
}

func (x *Option) GetMultiplier() *decimal.Decimal {
	if x != nil {
		return x.Multiplier
	}
	return nil
}

// Сессии
type ScheduleResponse_Sessions struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Тип сессии
	Type string `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	// Интервал сессии
	Interval      *interval.Interval `protobuf:"bytes,2,opt,name=interval,proto3" json:"interval,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScheduleResponse_Sessions) Reset() {
	*x = ScheduleResponse_Sessions{}
	mi := &file_grpc_tradeapi_v1_assets_assets_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScheduleResponse_Sessions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScheduleResponse_Sessions) ProtoMessage() {}

func (x *ScheduleResponse_Sessions) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_tradeapi_v1_assets_assets_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScheduleResponse_Sessions.ProtoReflect.Descriptor instead.
func (*ScheduleResponse_Sessions) Descriptor() ([]byte, []int) {
	return file_grpc_tradeapi_v1_assets_assets_service_proto_rawDescGZIP(), []int{7, 0}
}

func (x *ScheduleResponse_Sessions) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ScheduleResponse_Sessions) GetInterval() *interval.Interval {
	if x != nil {
		return x.Interval
	}
	return nil
}

var File_grpc_tradeapi_v1_assets_assets_service_proto protoreflect.FileDescriptor

const file_grpc_tradeapi_v1_assets_assets_service_proto_rawDesc = "" +
	"\n" +
	",grpc/tradeapi/v1/assets/assets_service.proto\x12\x17grpc.tradeapi.v1.assets\x1a\x1cgoogle/api/annotations.proto\x1a\x16google/type/date.proto\x1a\x19google/type/decimal.proto\x1a\x1agoogle/type/interval.proto\"\x12\n" +
	"\x10ExchangesRequest\"T\n" +
	"\x11ExchangesResponse\x12?\n" +
	"\texchanges\x18\x01 \x03(\v2!.grpc.tradeapi.v1.assets.ExchangeR\texchanges\"\x0f\n" +
	"\rAssetsRequest\"H\n" +
	"\x0eAssetsResponse\x126\n" +
	"\x06assets\x18\x01 \x03(\v2\x1e.grpc.tradeapi.v1.assets.AssetR\x06assets\"B\n" +
	"\x13OptionsChainRequest\x12+\n" +
	"\x11underlying_symbol\x18\x01 \x01(\tR\x10underlyingSymbol\"i\n" +
	"\x14OptionsChainResponse\x12\x16\n" +
	"\x06symbol\x18\x01 \x01(\tR\x06symbol\x129\n" +
	"\aoptions\x18\x02 \x03(\v2\x1f.grpc.tradeapi.v1.assets.OptionR\aoptions\")\n" +
	"\x0fScheduleRequest\x12\x16\n" +
	"\x06symbol\x18\x01 \x01(\tR\x06symbol\"\xcd\x01\n" +
	"\x10ScheduleResponse\x12\x16\n" +
	"\x06symbol\x18\x01 \x01(\tR\x06symbol\x12N\n" +
	"\bsessions\x18\x02 \x03(\v22.grpc.tradeapi.v1.assets.ScheduleResponse.SessionsR\bsessions\x1aQ\n" +
	"\bSessions\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x121\n" +
	"\binterval\x18\x02 \x01(\v2\x15.google.type.IntervalR\binterval\"0\n" +
	"\bExchange\x12\x10\n" +
	"\x03mic\x18\x01 \x01(\tR\x03mic\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"\x95\x01\n" +
	"\x05Asset\x12\x16\n" +
	"\x06symbol\x18\x01 \x01(\tR\x06symbol\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\x12\x16\n" +
	"\x06ticker\x18\x03 \x01(\tR\x06ticker\x12\x10\n" +
	"\x03mic\x18\x04 \x01(\tR\x03mic\x12\x12\n" +
	"\x04isin\x18\x05 \x01(\tR\x04isin\x12\x12\n" +
	"\x04type\x18\x06 \x01(\tR\x04type\x12\x12\n" +
	"\x04name\x18\a \x01(\tR\x04name\"\xa8\x03\n" +
	"\x06Option\x12\x16\n" +
	"\x06symbol\x18\x01 \x01(\tR\x06symbol\x128\n" +
	"\x04type\x18\x02 \x01(\x0e2$.grpc.tradeapi.v1.assets.Option.TypeR\x04type\x129\n" +
	"\rcontract_size\x18\x04 \x01(\v2\x14.google.type.DecimalR\fcontractSize\x129\n" +
	"\x0ftrade_first_day\x18\x05 \x01(\v2\x11.google.type.DateR\rtradeFirstDay\x127\n" +
	"\x0etrade_last_day\x18\x06 \x01(\v2\x11.google.type.DateR\ftradeLastDay\x12,\n" +
	"\x06strike\x18\a \x01(\v2\x14.google.type.DecimalR\x06strike\x124\n" +
	"\n" +
	"multiplier\x18\t \x01(\v2\x14.google.type.DecimalR\n" +
	"multiplier\"9\n" +
	"\x04Type\x12\x14\n" +
	"\x10TYPE_UNSPECIFIED\x10\x00\x12\r\n" +
	"\tTYPE_CALL\x10\x01\x12\f\n" +
	"\bTYPE_PUT\x10\x022\x9f\x04\n" +
	"\rAssetsService\x12y\n" +
	"\tExchanges\x12).grpc.tradeapi.v1.assets.ExchangesRequest\x1a*.grpc.tradeapi.v1.assets.ExchangesResponse\"\x15\x82\xd3\xe4\x93\x02\x0f\x12\r/v1/exchanges\x12m\n" +
	"\x06Assets\x12&.grpc.tradeapi.v1.assets.AssetsRequest\x1a'.grpc.tradeapi.v1.assets.AssetsResponse\"\x12\x82\xd3\xe4\x93\x02\f\x12\n" +
	"/v1/assets\x12\x9b\x01\n" +
	"\fOptionsChain\x12,.grpc.tradeapi.v1.assets.OptionsChainRequest\x1a-.grpc.tradeapi.v1.assets.OptionsChainResponse\".\x82\xd3\xe4\x93\x02(\x12&/v1/assets/{underlying_symbol}/options\x12\x85\x01\n" +
	"\bSchedule\x12(.grpc.tradeapi.v1.assets.ScheduleRequest\x1a).grpc.tradeapi.v1.assets.ScheduleResponse\"$\x82\xd3\xe4\x93\x02\x1e\x12\x1c/v1/assets/{symbol}/scheduleB&P\x01Z\"trade_api/v1/assets/assets_serviceb\x06proto3"

var (
	file_grpc_tradeapi_v1_assets_assets_service_proto_rawDescOnce sync.Once
	file_grpc_tradeapi_v1_assets_assets_service_proto_rawDescData []byte
)

func file_grpc_tradeapi_v1_assets_assets_service_proto_rawDescGZIP() []byte {
	file_grpc_tradeapi_v1_assets_assets_service_proto_rawDescOnce.Do(func() {
		file_grpc_tradeapi_v1_assets_assets_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_grpc_tradeapi_v1_assets_assets_service_proto_rawDesc), len(file_grpc_tradeapi_v1_assets_assets_service_proto_rawDesc)))
	})
	return file_grpc_tradeapi_v1_assets_assets_service_proto_rawDescData
}

var file_grpc_tradeapi_v1_assets_assets_service_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_grpc_tradeapi_v1_assets_assets_service_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_grpc_tradeapi_v1_assets_assets_service_proto_goTypes = []any{
	(Option_Type)(0),                  // 0: grpc.tradeapi.v1.assets.Option.Type
	(*ExchangesRequest)(nil),          // 1: grpc.tradeapi.v1.assets.ExchangesRequest
	(*ExchangesResponse)(nil),         // 2: grpc.tradeapi.v1.assets.ExchangesResponse
	(*AssetsRequest)(nil),             // 3: grpc.tradeapi.v1.assets.AssetsRequest
	(*AssetsResponse)(nil),            // 4: grpc.tradeapi.v1.assets.AssetsResponse
	(*OptionsChainRequest)(nil),       // 5: grpc.tradeapi.v1.assets.OptionsChainRequest
	(*OptionsChainResponse)(nil),      // 6: grpc.tradeapi.v1.assets.OptionsChainResponse
	(*ScheduleRequest)(nil),           // 7: grpc.tradeapi.v1.assets.ScheduleRequest
	(*ScheduleResponse)(nil),          // 8: grpc.tradeapi.v1.assets.ScheduleResponse
	(*Exchange)(nil),                  // 9: grpc.tradeapi.v1.assets.Exchange
	(*Asset)(nil),                     // 10: grpc.tradeapi.v1.assets.Asset
	(*Option)(nil),                    // 11: grpc.tradeapi.v1.assets.Option
	(*ScheduleResponse_Sessions)(nil), // 12: grpc.tradeapi.v1.assets.ScheduleResponse.Sessions
	(*decimal.Decimal)(nil),           // 13: google.type.Decimal
	(*date.Date)(nil),                 // 14: google.type.Date
	(*interval.Interval)(nil),         // 15: google.type.Interval
}
var file_grpc_tradeapi_v1_assets_assets_service_proto_depIdxs = []int32{
	9,  // 0: grpc.tradeapi.v1.assets.ExchangesResponse.exchanges:type_name -> grpc.tradeapi.v1.assets.Exchange
	10, // 1: grpc.tradeapi.v1.assets.AssetsResponse.assets:type_name -> grpc.tradeapi.v1.assets.Asset
	11, // 2: grpc.tradeapi.v1.assets.OptionsChainResponse.options:type_name -> grpc.tradeapi.v1.assets.Option
	12, // 3: grpc.tradeapi.v1.assets.ScheduleResponse.sessions:type_name -> grpc.tradeapi.v1.assets.ScheduleResponse.Sessions
	0,  // 4: grpc.tradeapi.v1.assets.Option.type:type_name -> grpc.tradeapi.v1.assets.Option.Type
	13, // 5: grpc.tradeapi.v1.assets.Option.contract_size:type_name -> google.type.Decimal
	14, // 6: grpc.tradeapi.v1.assets.Option.trade_first_day:type_name -> google.type.Date
	14, // 7: grpc.tradeapi.v1.assets.Option.trade_last_day:type_name -> google.type.Date
	13, // 8: grpc.tradeapi.v1.assets.Option.strike:type_name -> google.type.Decimal
	13, // 9: grpc.tradeapi.v1.assets.Option.multiplier:type_name -> google.type.Decimal
	15, // 10: grpc.tradeapi.v1.assets.ScheduleResponse.Sessions.interval:type_name -> google.type.Interval
	1,  // 11: grpc.tradeapi.v1.assets.AssetsService.Exchanges:input_type -> grpc.tradeapi.v1.assets.ExchangesRequest
	3,  // 12: grpc.tradeapi.v1.assets.AssetsService.Assets:input_type -> grpc.tradeapi.v1.assets.AssetsRequest
	5,  // 13: grpc.tradeapi.v1.assets.AssetsService.OptionsChain:input_type -> grpc.tradeapi.v1.assets.OptionsChainRequest
	7,  // 14: grpc.tradeapi.v1.assets.AssetsService.Schedule:input_type -> grpc.tradeapi.v1.assets.ScheduleRequest
	2,  // 15: grpc.tradeapi.v1.assets.AssetsService.Exchanges:output_type -> grpc.tradeapi.v1.assets.ExchangesResponse
	4,  // 16: grpc.tradeapi.v1.assets.AssetsService.Assets:output_type -> grpc.tradeapi.v1.assets.AssetsResponse
	6,  // 17: grpc.tradeapi.v1.assets.AssetsService.OptionsChain:output_type -> grpc.tradeapi.v1.assets.OptionsChainResponse
	8,  // 18: grpc.tradeapi.v1.assets.AssetsService.Schedule:output_type -> grpc.tradeapi.v1.assets.ScheduleResponse
	15, // [15:19] is the sub-list for method output_type
	11, // [11:15] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_grpc_tradeapi_v1_assets_assets_service_proto_init() }
func file_grpc_tradeapi_v1_assets_assets_service_proto_init() {
	if File_grpc_tradeapi_v1_assets_assets_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_grpc_tradeapi_v1_assets_assets_service_proto_rawDesc), len(file_grpc_tradeapi_v1_assets_assets_service_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_grpc_tradeapi_v1_assets_assets_service_proto_goTypes,
		DependencyIndexes: file_grpc_tradeapi_v1_assets_assets_service_proto_depIdxs,
		EnumInfos:         file_grpc_tradeapi_v1_assets_assets_service_proto_enumTypes,
		MessageInfos:      file_grpc_tradeapi_v1_assets_assets_service_proto_msgTypes,
	}.Build()
	File_grpc_tradeapi_v1_assets_assets_service_proto = out.File
	file_grpc_tradeapi_v1_assets_assets_service_proto_goTypes = nil
	file_grpc_tradeapi_v1_assets_assets_service_proto_depIdxs = nil
}
